runtime: custom
env: flex
runtime_config:  # Optional
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS
manual_scaling:
  instances: 1
resources:
  memory_gb: 2.0
health_check:
  enable_health_check: False
