CREATE TABLE USERS (
  ID           INT          NOT NULL AUTO_INCREMENT,
  EMAIL        VARCHAR(100) NOT NULL,
  PASSWORD     VARCHAR(100) NOT NULL,
  ENABLED      BOOLEAN               DEFAULT TRUE,
  TOKEN_EXPIRED BOOLEAN               DEFAULT FALSE,
  PERSON_ID    INT,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLES (
  ID   INT          NOT NULL  AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE USERS_ROLES (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE PERSONS (
  ID         INT          NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME  VARCHAR(100) NOT NULL,
  ACCOUNT_ID INT,
  PRIMARY KEY (ID)
);
ALTER TABLE USERS
  ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSONS (ID);

CREATE TABLE ACCOUNTS (
  ID    INT NOT NULL AUTO_INCREMENT,
  MONEY DECIMAL(6, 2),
  PRIMARY KEY (ID)
);
ALTER TABLE PERSONS
  ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);


CREATE TABLE PRODUCTS (
  ID          INT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(500),
  PRICE       DECIMAL(5, 2),
  CURRENCY    VARCHAR (3),
  IMAGE       BLOB,
  PRIMARY KEY (ID),

);

CREATE TABLE USER_ORDERS (
  ID           INT NOT NULL AUTO_INCREMENT,
  AMOUNT       DECIMAL(6, 2),
  DATE_CREATED TIMESTAMP,
  USER_ID      INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),

);

CREATE TABLE ORDERED_PRODUCTS (
  USER_ORDER_ID INT,
  PRODUCT_ID    INT,
  FOREIGN KEY (USER_ORDER_ID) REFERENCES USER_ORDERS (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)

)



