create table USERS(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR (100) not null,
LAST_NAME VARCHAR (100) not null,
EMAIL VARCHAR (100) not null,
PASSWORD VARCHAR (100) not null,
ACCOUNT_ID INT,
PRIMARY KEY (ID)
);

create TABLE ACCOUNTS(
  ID INT NOT NULL AUTO_INCREMENT,
  MONEY DECIMAL(6,2),
  PRIMARY KEY (ID)
);

ALTER TABLE USERS ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID);

CREATE TABLE USERS_ORDERS(
  ID INT NOT NULL AUTO_INCREMENT,
  AMOUNT DECIMAL(6,2),
  DATE_CREATED TIMESTAMP,
  USER_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);


CREATE TABLE PRODUCTS(
  ID INT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(500),
  PRICE DECIMAL(5,2),
  IMAGE BLOB,
  USERS_ORDERS_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERS_ORDERS_ID) REFERENCES USERS_ORDERS(ID)

);


