INSERT INTO ACCOUNTS (MONEY) VALUES (300.00);

INSERT INTO PERSONS (FIRST_NAME, LAST_NAME, ACCOUNT_ID) VALUES
  ('Tomasz', 'Zielichowski', '1');

INSERT INTO USERS (EMAIL, PASSWORD, ENABLED, TOKEN_EXPIRED, PERSON_ID) VALUES
  ('to@zie.pl', '$2a$04$EtkFrFJc0s2wOIfGy40lT.fte2kJCxhsePOjRrdOAkCwzBLTHswqm', TRUE, TRUE, '1');

INSERT  INTO ROLES(NAME) VALUES ('ROLE_ADMIN');
INSERT  INTO ROLES(NAME) VALUES ('ROLE_USER');

INSERT INTO USERS_ROLES(USER_ID,ROLE_ID) VALUES ('1','1');
INSERT INTO USERS_ROLES(USER_ID,ROLE_ID) VALUES ('1','2');


INSERT INTO USER_ORDERS (AMOUNT, DATE_CREATED, USER_ID) VALUES (1, '2013-08-05 18:19:03', 1);
