INSERT INTO ACCOUNTS (MONEY) VALUES (300.00);
INSERT INTO USERS (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,ACCOUNT_ID) VALUES
('Tomo','Zie','to@zie.pl','$2a$04$EtkFrFJc0s2wOIfGy40lT.fte2kJCxhsePOjRrdOAkCwzBLTHswqm','1');

INSERT INTO USERS_ORDERS(AMOUNT, DATE_CREATED, USER_ID) VALUES (1,'2013-08-05 18:19:03',1);
